# Generated by Django 5.1.6 on 2025-05-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
