# Generated by Django 5.1.6 on 2025-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
