# Generated by Django 5.1.6 on 2025-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_fare_train_base_fare_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
