# Generated by Django 5.1.6 on 2025-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_seat_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
