# Generated by Django 5.1.6 on 2025-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ticket_origin_alter_ticket_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
