# Generated by Django 5.1.6 on 2025-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('NORMAL', 'Normal')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
