# Generated by Django 5.1.6 on 2025-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
