# Generated by Django 5.1.6 on 2025-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='food_required',
            field=models.BooleanField(default=False),
        ),
    ]
