# Generated by Django 5.1.6 on 2025-05-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ticket_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='age',
        ),
    ]
