# Generated by Django 5.1.6 on 2025-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_ticket_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
