# Generated by Django 5.1.6 on 2025-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pantryitem_remove_ticket_food_required_bookingpantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='wants_pantry',
            field=models.BooleanField(default=False),
        ),
    ]
