# Generated by Django 5.1.6 on 2025-05-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_wants_pantry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='wants_pantry',
            new_name='food_required',
        ),
    ]
