# Generated by Django 5.1.6 on 2025-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seat_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='train',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
