# Generated by Django 5.1.6 on 2025-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_train_seat_info_alter_train_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='train',
            name='booked_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
