# Generated by Django 5.1.6 on 2025-05-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_name_alter_train_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
