# Generated by Django 5.1.6 on 2025-05-12 10:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_train_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(db_index=True, default=api.models.generate_pnr, max_length=8),
        ),
    ]
