# Generated by Django 5.1.6 on 2025-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_ticket_pnr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
    ]
